### PR TITLE
add DOM3 mouseenter and mouseleave

### PR DESCRIPTION
**Pull request by SergioCrisostomo**

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Thanks for the pull request.

This events are not fired in old versions of FF / Chrome / etc.

They should probably be feature tested.

**Comment by SergioCrisostomo** [comment]
@justinbmeyer added a `if` feature check. I supose it was that what you had in mind...

**Comment by piuccio** [comment]
I'm not sure it's this simple.

If `el` is contained inside `last`, `enter` and `leave` shouldn't be fired.
https://developer.mozilla.org/en-US/docs/Web/Events/mouseenter

**Comment by kdillon** [comment]
This should be resolved by recent changes.

If this is still a concern, let me know

**Pull request closed without merging**
