### PR TITLE
#99 - make npm install && npm test work

### PR DESCRIPTION
**Pull request by mickmcgrath13**
add grunt-contrib-uglify, phantomjs to package.json | update test file reference in gruntfile | update testee version

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks!  You can merge when tests pass.

**Comment by mickmcgrath13** [comment]
Should there be a version update or anything?

**Comment by matthewp** [comment]
Well we don't do that in a PR, but in this case we don't need to bump the version since there is no fixes to user code.

**Comment by mickmcgrath13** [comment]
Okay, thx

**Pull request merged**
