### PR TITLE
Very alpha version of a tool that I am working-on to track the events…

### PR DESCRIPTION
**Pull request by kdillon**
… that go to a particular element. This will enable users to accurately record events, and compare to the events that FuncUnit generates.

Unfortunately some junk that wasn't supposed to be uploaded accidentally got put into this project (such as: non-resized and unrelated images), so I will go back and remove those.

### CODE REVIEW

**Comment by chasenlehara** [comment]
@kdillon Let me know if you need any help removing the images. We can amend your original commit so it’s like they were never added. 😊

**Comment by kdillon** [comment]
Thanks, that would be great. Honestly, I don't know how to modify commits in git. I find this tool to be extremely counter-intuitive. Things that should be trivial seem unsupported, to the point where I just give up and delete stuff later.

**Comment by justinbmeyer** [comment]
Dillon, this is great!  You find git or some other tool counter-intuitive? Thanks.

**Comment by kdillon** [comment]
Hi Justin,

Glad that you approve. I am going to write up a couple demo pages to show this tool's flexibility and usefulness, and I'm going to improve its functionality going-forward. (also, some of the code is a bit hacky)

In terms of counter-intuitive, the GIT submission review allows you to edit-in-place any text documents, but not binary files. It seems like there should be a "delete" button. If there is one, I haven't found it.

**Pull request merged**
